### ISSUE TITLE
kaptive convert args.input typo

### ISSUE THREAD

**Issue by mthang** [klebgenomics/Kaptive#61]
I ran into an error below with kaptive convert (kaptive version 3.2.1). I found a typo in cli.py in line 128 where "inputf" is used in def convert_subparser(subparsers), but args.input is used in line 247. I edited the cli.py by replacing args.input with args.inputf in line 247. it works.

Traceback (most recent call last):
  File "/home/mthang/venv_kaptive/bin/kaptive", line 10, in <module>
    sys.exit(cli())
             ~~~^^
  File "/home/mthang/venv_kaptive/lib/python3.14/site-packages/kaptive/cli.py", line 252, in cli
    for line in args.input:
                ^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'input'. Did you mean: 'inputf'?

**Comment by tomdstanton** [comment]
Thanks @mthang 
I'm working on a new version of Kaptive (v3.3) releasing next week which will solve this issue.

May I ask what format you're trying to convert your results to?

**Comment by mthang** [comment]
@tomdstanton it's great to know that the kaptive (v3.3) is coming soon. Regarding the format that I was converting to , it's all format because the issue was due to the inconsistent "args.inputf" vs "args.input" . Would you please either using "args.input" or "args.inputf" for both convert_subparser function

In convert_subparser, args.inputf is used
   opts.add_argument('inputf', help=f'{_DIST} JSON lines file or - for stdin', type=argparse.FileType('rt'),
                      metavar='json')

In elif args.subparser_name == 'convert': , the args.input is used
        for line in args.input:
            if result := parse_result(line, args.db, args.regex, args.samples, args.loci):
                result.write(args.tsv, args.json, args.fna, args.ffn, args.faa, args.plot, args.plot_fmt)


Below is the failed job: 
 
kaptive convert kpsc_k kaptive_results_k.json --tsv test_k.tsv --ffn test_k.ffn       
Traceback (most recent call last):
  File "/home/mthang/venv_kaptive/bin/kaptive", line 10, in <module>
    sys.exit(cli())
             ~~~^^
  File "/home/mthang/venv_kaptive/lib/python3.14/site-packages/kaptive/cli.py", line 252, in cli
    for line in args.input:
                ^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'input'. Did you mean: 'inputf'?

**Comment by mthang** [comment]
@tomdstanton I reopen this issue because I am running into another issue on generating plot.  is this args.plot_fmt in your script matching the --plot-fmt in the command line ? 

**kaptive convert kpsc_k kaptive_results_k.json -p test.png --plot-fmt png**
Traceback (most recent call last):
  File "/venv_kaptive/bin/kaptive", line 10, in <module>
    sys.exit(cli())
             ~~~^^
  File "/venv_kaptive/lib/python3.14/site-packages/kaptive/cli.py", line 254, in cli
    result.write(args.tsv, args.json, args.fna, args.ffn, args.faa, args.plot, **args.plot_fmt**)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv_kaptive/lib/python3.14/site-packages/kaptive/typing.py", line 235, in write
    ax = self.format(plot_fmt).plot(figure_width=18)[0]  # type: 'matplotlib.axes.Axes'
         ~~~~~~~~~~~^^^^^^^^^^
  File "/venv_kaptive/lib/python3.14/site-packages/kaptive/typing.py", line 215, in format
    raise ValueError(f"Unknown format specifier {format_spec}")
ValueError: Unknown format specifier png

**Comment by tomdstanton** [comment]
I removed the plotting functionality in Kaptive v3.2.1 to keep the library lightweight - it will be returned in v3.3 as an optional extra and to power the new Kaptive-Web interface.

For now, you can try kaptive-plot to generate plots:
https://github.com/tomdstanton/kaptive-plot
